// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgffjmbbzamwydpwxwkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnZmZqbWJiemFtd3lkcHd4d2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMzk2NjYsImV4cCI6MjA3NjcxNTY2Nn0.a1WuDUJ1Hb625LV6hMCvRQ9cOdE1LwRq8WzlEKG21lA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});